server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/citizen_db
    username: root
    password: Ajay@1999
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  application:
    name: CITIZEN-SERVICE
